import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['Outfit', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(0, 0, 0, 0.1)',
        'glow': '0 0 40px rgba(102, 126, 234, 0.3)',
        'glow-lg': '0 0 60px rgba(102, 126, 234, 0.4)',
        'card': '0 4px 24px rgba(0, 0, 0, 0.06)',
        'card-hover': '0 12px 40px rgba(0, 0, 0, 0.12)',
      },
      animation: {
        'float': 'float 3s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'slide-in': 'slide-in-right 0.3s ease-out forwards',
        'slide-out': 'slide-out-right 0.3s ease-out forwards',
        'fade-in': 'fade-in 0.3s ease-out forwards',
        'scale-in': 'scale-in 0.3s ease-out forwards',
      },
      backdropBlur: {
        'xs': '2px',
      },
      transitionDuration: {
        '400': '400ms',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      "nord",
      "forest",
      {
        light: {
          'primary': '#667eea',
          'primary-content': '#ffffff',
          'secondary': '#764ba2',
          'secondary-content': '#ffffff',
          'accent': '#4facfe',
          'accent-content': '#ffffff',
          'neutral': '#1f2937',
          'neutral-content': '#f9fafb',
          'base-100': '#ffffff',
          'base-200': '#f8fafc',
          'base-300': '#e2e8f0',
          'base-content': '#1e293b',
          'info': '#0ea5e9',
          'info-content': '#ffffff',
          'success': '#10b981',
          'success-content': '#ffffff',
          'warning': '#f59e0b',
          'warning-content': '#ffffff',
          'error': '#ef4444',
          'error-content': '#ffffff',
        },
        dark: {
          'primary': '#818cf8',
          'primary-content': '#ffffff',
          'secondary': '#a78bfa',
          'secondary-content': '#ffffff',
          'accent': '#67e8f9',
          'accent-content': '#0f172a',
          'neutral': '#1e293b',
          'neutral-content': '#f1f5f9',
          'base-100': '#0f172a',
          'base-200': '#1e293b',
          'base-300': '#334155',
          'base-content': '#f1f5f9',
          'info': '#38bdf8',
          'info-content': '#0f172a',
          'success': '#34d399',
          'success-content': '#0f172a',
          'warning': '#fbbf24',
          'warning-content': '#0f172a',
          'error': '#f87171',
          'error-content': '#0f172a',
        },
      },
    ],
    darkTheme: 'forest',
    base: true,
    styled: true,
    utils: true,
  },
}
export default config